export const BUSCAR_EQUIPES = 'BUSCAR_EQUIPES';
export const SELECIONAR_EQUIPE = 'SELECIONAR_EQUIPE';
export const SALVAR_EQUIPE = 'SALVAR_EQUIPE';
export const EXCLUIR_EQUIPE = 'EXCLUIR_EQUIPE';

export const BUSCAR_ATLETAS = 'BUSCAR_ATLETAS';
export const SELECIONAR_ATLETA = 'SELECIONAR_ATLETA';
export const SALVAR_ATLETA = 'SALVAR_ATLETA';
export const EXCLUIR_ATLETA = 'EXCLUIR_ATLETA';
