name: main
on:
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: webAppAction-wes
  MY_VARIABLE: heder
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Build
        run: |
          echo "action_state=cat tf.plan" >> "$GITHUB_ENV"
          echo "New my variable: $MY_VARIABLE"
          echo "Directory a the source: ${{ env.AZURE_WEBAPP_NAME }}"
          cd src
          echo cat tf.plan >> ${{ env.AZURE_WEBAPP_NAME }}
          echo "Novo valor: ${{ env.AZURE_WEBAPP_NAME }}"
        shell: bash
      - name: teste
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Heder00df
          minimum-approvals: 1
          issue-title: ${{env.action_state}}
          issue-body: ${{vars.LOG}}
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
      - name: Deploy to production
        run: echo ${{env.action_state}}
