name: main
on:
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: webAppAction-wes
  MY_VARIABLE: heder
jobs:
  my_job:
      runs-on: ubuntu-latest
      steps:
        - name: My Step
          run: |
            # Definir o valor da variável de ambiente
            echo "new_value" >> $GITHUB_ENV
            # Exibir o valor da variável de ambiente
            echo "My variable: $MY_VARIABLE"
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Build
        run: |
          echo "Directory a the source: ${{ env.AZURE_WEBAPP_NAME }}"
          cd src
          echo cat tf.plan >> ${{ env.AZURE_WEBAPP_NAME }}
          echo "Novo valor: ${{ env.AZURE_WEBAPP_NAME }}"         
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Heder00df
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
      - name: Deploy to production
        run: echo deploying
