name: main
on:
  workflow_dispatch:

jobs:
  build:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  approval:
    name: Approval
    runs-on: ubuntu-latest
    environment: 'approval'
    needs: build
    steps:
      - name: Deploy to production
        run: echo deploying
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy to production
        run: echo deploying
