name: main
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: 'approval'
    needs: build
    steps:
      - name: Deploy to production
        run: echo deploying
