name: My Workflow

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: my_value

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: |
          # Definir o valor da variável de ambiente
          echo "new_value" >> $GITHUB_ENV
          # Exibir o valor da variável de ambiente
          echo "My variable: $MY_VARIABLE"
